
# A simple makefile for compiling on linux
# if you are following the guide in the README

# Uncomment to use clang instead of g++
# CXX = g++
VERBOSE=on
#OMP=on
# Uncomment for debug i gnformation
DEBUG = on
#CXXFLAGS = -DFPEXCEPT #-DSUNDIALS_DEBUG

SUNDIALS_DIR=$(SUNDIALS_ROOT)
#TOML11_DIR = /home/ian/projects/toml11
#EIGEN_DIR = /usr/include/eigen3

XLA_FFI=on
CUDA=on

#JAX_XLA_INCLUDES = -I$$(python3-config --prefix)/lib/python3.12/site-packages/jaxlib/include
