include Makefile.local

CXX ?= g++

STD=c++23

ifdef OMP
CXXFLAGS += -fopenmp
else
CXXFLAGS += -Wno-unknown-pragmas
endif

CXXFLAGS += -Wno-parentheses -Wno-deprecated-literal-operator

# Emit a .d file per object listing every header it includes, so touching a
# header rebuilds exactly what depends on it. The hand-maintained $(HEADERS)
# list this replaces was missing Types.hpp, DGApprox.hpp, NetCDFIO.hpp and all
# of the Py*.hpp headers, so edits to those silently left stale objects (and a
# stale unit-test binary that still passed).
CXXFLAGS += -MMD -MP

ifdef COVERAGE
# Coverage needs -O0 and no LTO: optimisation and -flto destroy the mapping from
# machine code back to source lines, so gcov reports become meaningless.
# -fprofile-abs-path keeps .gcno references absolute so gcovr can resolve sources
# when make recurses into Tests/UnitTests.
CXXFLAGS += -fPIC -g -O0 --coverage -fprofile-abs-path -fno-inline -fno-inline-small-functions -fno-default-inline --std=$(STD) -Wall -Wno-unused-variable -pedantic
LDFLAGS  += --coverage
# gcov must match the compiler that produced the .gcno files.
GCOV ?= $(subst g++,gcov,$(CXX))
else ifdef DEBUG
CXXFLAGS += -fPIC -DDEBUG -DPHYSICS_DEBUG -g -O0 --std=$(STD) -Wall -Werror -Wno-error=unused-variable -pedantic
else
CXXFLAGS += -fPIC -O3 -flto=auto -march=native --std=$(STD) -Wall -Wno-unused-variable -Werror -pedantic
endif

GCOV ?= gcov

ifdef VERBOSE
CXXFLAGS += -DVERBOSE
endif

SUNDIALS_DIR ?= /usr/local

SUNDIALS_INC ?=$(realpath $(SUNDIALS_DIR)/include)
SUNDIALS_LIB ?=$(realpath $(SUNDIALS_DIR)/lib)

ifeq ($(strip $(SUNDIALS_INC)),)
$(error "Sundials include directory not found at $(SUNDIALS_DIR)/include")
endif

ifeq ($(strip $(SUNDIALS_LIB)),)
SUNDIALS_LIB =$(realpath $(SUNDIALS_DIR)/lib64)

ifeq ($(strip $(SUNDIALS_LIB)),)
$(error "Sundials compiled library directory not found at $(SUNDIALS_DIR)/lib or $(SUNDIALS_DIR)/lib64")
endif
endif

SUNFLAGS=-I$(SUNDIALS_INC)
SUN_LINK_FLAGS = -L$(SUNDIALS_LIB) -Wl,-rpath $(SUNDIALS_LIB) -lsundials_core -lsundials_ida -lsundials_nvecserial

TOML11_DIR ?= ./extern/toml11/include
TOML_FLAGS = -I$(realpath $(TOML11_DIR))

CXXFLAGS += $(TOML_FLAGS) $(SUNFLAGS)

ifdef BOOST_DIR
	BOOST_FLAGS = -I$(realpath $(BOOST_DIR))
	CXXFLAGS += $(BOOST_FLAGS)
endif

NETCDF_LINK_FLAGS =

ifdef NETCDF_DIR
	CXXFLAGS += -I$(realpath $(NETCDF_DIR))/include
	NETCDF_LINK_FLAGS = -L$(realpath $(NETCDF_DIR))/lib -Wl,-rpath $(realpath $(NETCDF_DIR))/lib
ifndef NETCDF_CXX_DIR
	NETCDF_CXX_DIR = $(NETCDF_DIR)
endif
endif

ifdef NETCDF_CXX_DIR
	CXXFLAGS += -I$(realpath $(NETCDF_CXX_DIR))/include
	NETCDF_LINK_FLAGS += -L$(realpath $(NETCDF_CXX_DIR))/lib -Wl,-rpath $(realpath $(NETCDF_CXX_DIR))/lib
endif
	
ifndef NETCDF_CXX_LIB
	NETCDF_LINK_FLAGS += -lnetcdf -lnetcdf_c++4
else
	NETCDF_LINK_FLAGS += -lnetcdf -l$(NETCDF_CXX_LIB)
endif

ifdef EIGEN_DIR
	EIGENFLAGS = -I$(EIGEN_DIR)
	CXXFLAGS += $(EIGENFLAGS)
else 
	EIGENFLAGS =
endif 

EIG_FLAGS = -DEIGEN_USE_BLAS 
EIG_LINK_FLAGS= -lblas -Wl,--no-as-needed -lpthread -lm -ldl

AUTODIFF_DIR ?= ./extern/autodiff/

AUTODIFF_INC = $(realpath $(AUTODIFF_DIR))

AUTODIFF_FLAGS = -I$(AUTODIFF_INC)

CXXFLAGS += $(EIG_FLAGS) $(AUTODIFF_FLAGS)

LDFLAGS += $(SUN_LINK_FLAGS) $(NETCDF_LINK_FLAGS) $(EIG_LINK_FLAGS)

PYTHON_HEADERS=PyTransportSystem.hpp PyAdjointProblem.hpp PyGrid.hpp PyRunner.hpp PyIntegrator.hpp
PYTHON_OBJECTS=Python.cpp PyRunner.cpp
ifdef XLA_FFI
	JAX_DIR = $(shell python -c 'import jaxlib; import os; print( os.path.dirname(jaxlib.__file__) )')
	JAX_XLA_INCLUDES=-I$(JAX_DIR)/include
ifdef CUDA
	PYTHON_FLAGS=-DCUDA
else
	PYTHONFLAGS=
endif
	PYTHON_FLAGS+=-DXLA_FFI -Wno-attributes -Wno-return-type -Wno-unused-but-set-variable -Wno-changes-meaning -Wno-sign-compare
	PYTHON_HEADERS+=ffi.hpp
	
else
	JAX_XLA_INCLUDES=
	PYTHON_FLAGS=
endif

Makefile.local:
	$(error You need to provide a Makefile.local for your machine. Try copying Makefile.local.example)


