include Makefile.local

CXX ?= g++

STD=c++23

ifdef OMP
CXXFLAGS += -fopenmp -DEIGEN_DONT_PARALLELIZE
else
CXXFLAGS += -Wno-unknown-pragmas
endif

CXXFLAGS += -Wno-parentheses -Wno-deprecated-literal-operator

ifdef DEBUG
CXXFLAGS += -fPIC -DDEBUG -DPHYSICS_DEBUG -g -O0 --std=$(STD) -Wall -Werror -Wno-error=unused-variable -pedantic
else
CXXFLAGS += -fPIC -DPHYSICS_DEBUG -O3 -flto=auto -march=native --std=$(STD) -Wall -Wno-unused-variable -Werror -pedantic
endif

SUNDIALS_DIR ?= /usr/local

SUNDIALS_INC ?=$(realpath $(SUNDIALS_DIR)/include)
SUNDIALS_LIB ?=$(realpath $(SUNDIALS_DIR)/lib)

ifeq ($(strip $(SUNDIALS_INC)),)
$(error "Sundials include directory not found at $(SUNDIALS_DIR)/include")
endif

ifeq ($(strip $(SUNDIALS_LIB)),)
SUNDIALS_LIB ?=$(realpath $(SUNDIALS_DIR)/lib64)
ifeq ($(strip $(SUNDIALS_LIB)),)
$(error "Sundials compiled library directory not found at $(SUNDIALS_DIR)/lib or $(SUNDIALS_DIR)/lib64")
endif
endif

SUNFLAGS=-I$(SUNDIALS_INC)
SUN_LINK_FLAGS = -L$(SUNDIALS_LIB) -Wl,-rpath $(SUNDIALS_LIB) -lsundials_core -lsundials_ida -lsundials_nvecserial

TOML11_DIR ?= ./extern/toml11/include
TOML_FLAGS = -I$(realpath $(TOML11_DIR))

CXXFLAGS += $(TOML_FLAGS) $(SUNFLAGS)

ifdef BOOST_DIR
	BOOST_FLAGS = -I$(realpath $(BOOST_DIR))
	CXXFLAGS += $(BOOST_FLAGS)
endif

NETCDF_LINK_FLAGS =

ifdef NETCDF_DIR
	CXXFLAGS += -I$(realpath $(NETCDF_DIR))/include
	NETCDF_LINK_FLAGS = -L$(realpath $(NETCDF_DIR))/lib -Wl,-rpath $(realpath $(NETCDF_DIR))/lib
ifndef NETCDF_CXX_DIR
	NETCDF_CXX_DIR = $(NETCDF_DIR)
endif
endif

ifdef NETCDF_CXX_DIR
	CXXFLAGS += -I$(realpath $(NETCDF_CXX_DIR))/include
	NETCDF_LINK_FLAGS += -L$(realpath $(NETCDF_CXX_DIR))/lib -Wl,-rpath $(realpath $(NETCDF_CXX_DIR))/lib
endif
	
ifndef NETCDF_CXX_LIB
	NETCDF_LINK_FLAGS += -lnetcdf -lnetcdf_c++4
else
	NETCDF_LINK_FLAGS += -lnetcdf -l$(NETCDF_CXX_LIB)
endif

ifdef EIGEN_DIR
	EIGENFLAGS = -I$(EIGEN_DIR)
	CXXFLAGS += $(EIGENFLAGS)
else 
	EIGENFLAGS =
endif 

EIG_LINK_FLAGS=-Wl,--no-as-needed -lpthread -lm -ldl

AUTODIFF_DIR ?= ./extern/autodiff/

AUTODIFF_INC = $(realpath $(AUTODIFF_DIR))

AUTODIFF_FLAGS = -I$(AUTODIFF_INC)

CXXFLAGS += $(AUTODIFF_FLAGS)

LDFLAGS += $(SUN_LINK_FLAGS) $(NETCDF_LINK_FLAGS) $(EIG_LINK_FLAGS)

Makefile.local:
	$(error You need to provide a Makefile.local for your machine. Try copying Makefile.local.example)


