[configuration]


Polynomial_degree = 3
Grid_size = 20
Lower_boundary =  -1.0
Upper_boundary =  1.0

t_final = 0.5
delta_t = 0.1

Relative_tolerance = 1.0e-3
Absolute_tolerance = 1.0e-2

PythonModuleName = "jax_diffusion"
PythonModuleFile = "jax_diffusion.py"
TransportSystem = "JAXNonlinearDiffusion"

[DiffusionProblem]

SourceCentre = 0.0
D = 1.0
a = 2.0

