[configuration]

PolynomialDegree = 3
GridSize = 20
LowerBoundary = -1.0
UpperBoundary =  1.0

t_final = 0.5
delta_t = 0.1

Relative_tolerance = 1.0e-3
Absolute_tolerance = 1.0e-2

PythonModuleName = "toy_model"
PythonModuleFile = "toy_model.py"
TransportSystem = "ToyModel1"
