[configuration]
PolynomialDegree = 3
GridSize = 10
LowerBoundary = 0.0
UpperBoundary = 1.0
tau = 10.0
t_final = 5.0
delta_t = 0.25
Relative_tolerance = 0.0001
Absolute_tolerance = 0.001
PythonModuleName = "jax_nonlinear_adjoint"
PythonModuleFile = "jax_nonlinear_adjoint.py"
TransportSystem = "JAXNonlinearDiffusion"
solveAdjoint = true

[DiffusionProblem]
D = 10.0
SourceCentre = 0.3
a = 0.0
