[configuration]

restart = false
# RestartFile = "/home/eatocco/projects/MaNTA/runs/CMFX.restart.nc"

MinStepSize = 1e-11
TransportSystem = "MirrorPlasma"

Polynomial_degree = 6
Grid_size = 30
High_Grid_Boundary = true
Lower_Boundary_Fraction = 0.2
Upper_Boundary_Fraction = 0.2

OutputPoints = 1000

#Lower_boundary = 0.004712388980385
#Upper_boundary = 0.117809724509617
Lower_boundary = 0.01
Upper_boundary = 0.2
tau = 100000.0
t_final = 0.5
delta_t = 1e-2
Relative_tolerance = 1.0e-2
# Per-variable 
Absolute_tolerance = 1.0e-4

[MirrorPlasma]

lowerBoundaryConditions = [false,true,false,true]
upperBoundaryConditions = [false,false,false,true]

MinDensity = 0.0
MinTemp = 0.0
RelaxFactor = 0.0

SourceCap = 200000.0
SourceRampup = 1.0e-3
useAmbipolarPhi = true
useConstantVoltage = true
PlasmaVoltage = 70e3
CurrentDecay = 1.0e-3

# gamma = 100.0
# gamma_d = 0.001
# gamma_h = 5e7

gamma = 1e5
gamma_d = 0.0
gamma_h = 1e5

# ConstantProfiles = ["Density"]
useNcBField = false
MagneticFieldData = "/home/eatocco/projects/python/Bfield.nc"

# MagneticFieldData = "/home/eatocco/projects/MaNTA/Bfield.nc"
Bz = 0.34
Rm = 10.0
Lz = 0.6
FieldSlope = 0.0

# IRadial = 10000.0
IRadial = 0.05
MachWidth = 0.1

EdgeDensity = 2e-2
InitialDensity = 0.02

EdgeElectronTemperature = 0.1
EdgeIonTemperature = 0.1
InitialElectronTemperature = 0.1
InitialIonTemperature = 0.1

InitialMachNumber = 7.0
LowerMachNumber = 3.5
UpperMachNumber = 3.5

IonSpecies = "Hydrogen"

useNeutralsModel = false
NeutralDensity = 0.0
# NeutralDensity = 0.0

# LowerPS = 5500.0
# # LowerPS = 1500.0
# UpperPS = 2500.0
UniformHeatSource = 0.0

LowerPS = 1000.0
UpperPS = 2000.0


ParticleSourceCenter = 0.01
ParticleSourceWidth = 0.01
lowNDiffusivity = 0.01
lowNThreshold = 50.0
lowPDiffusivity = 0.01
lowPThreshold = 50.0
lowLDiffusivity = 0.01
lowLThreshold = 500.0

TeDiffusivity = 0.05

transitionLength = 10.0

# lowNDiffusivity = 100.0
# lowNThreshold = 0.05
# lowPDiffusivity = 150.0
# lowPThreshold = 0.05
# lowLDiffusivity = 100.0
# lowLThreshold = 0.05

# TeDiffusivity = 0.1

# transitionLength = 50.0

# lowNDiffusivity = 100.0
# lowNThreshold = 0.05
# lowPDiffusivity = 50.0
# lowPThreshold = 0.05
# lowLDiffusivity = 100.0
# lowLThreshold = 0.05

# TeDiffusivity = 0.5

# transitionLength = 50.0