[configuration]

restart = false
MinStepSize = 1e-10
TransportSystem = "MirrorPlasma"

Polynomial_degree = 6
Grid_size = 33
High_Grid_Boundary = true
Lower_Boundary_Fraction = 0.1
Upper_Boundary_Fraction = 0.1

OutputPoints = 1000

Lower_boundary = 0.05   # Upper and lower boundary in volume units, to get R do sqrt( V / (pi * Lz))
Upper_boundary = 0.2

tau = 100000.0
t_final = 0.1
delta_t = 0.01

Relative_tolerance = 1.0e-2
Absolute_tolerance = 1.0e-3 # can also do per-variable here

[MirrorPlasma]

# Boundary conditions for each channel, true = dirichlet, false = neumann, default all Dirichlet
# [Density, Ion Energy, Electron Energy, Angular Momentum]
lowerBoundaryConditions = [false,true,false,true]    # I found this combination to work the best, but results may vary 
upperBoundaryConditions = [false,false,false,true]

SourceCap = 500000.0  # Maximum allowed source - the only source that gets this large is the viscous heating
SourceRampup = 1.0e-4 # Rampup the sources using a tanh function over this timescale

useAmbipolarPhi = true # Solve for the ambipolar potential, recommended to leave this set to true

#---------- Voltage controller settings ----------#
useConstantVoltage = true # Use PID controller to maintain a set voltage
PlasmaVoltage = 100e3 

CurrentDecay = 5.0e-3 # Give an initial current (IRadial) that decays over the specified timescale
IRadial = 0.2

# PID controller settings
gamma   = 100000.0   # Linear coef
gamma_d = 2000.0    # Time derivative coef
gamma_h = 1e3      # Integral coef

#---------- Magnetic field settings ----------#

useNcBField = false # Allows for setting of magnetic field from a netCDF file 
MagneticFieldData = "/home/eatocco/projects/python/Bfield.nc" # update with netCDF file to your field

# If using a straight magnetic field, set parameters here
Bz = 0.34        # Central magnetic field value
Rm = 10.0        # Mirror ratio at R = 0
Lz = 0.6         # Length of magnetic well
FieldSlope = 0.2 # Decaying slope 

#---------- Initial/boundary condition settings ----------#
# NOTE: If using Neumann boundary conditions, initial boundary values will likely not remain consistent


MachWidth = 0.1 # The initial Mach number is flat in the middle and decays at the edge. The width of the edge region is set here
InitialMachNumber = 7.0 # Initial central Mach number

# Boundary value of Mach number
LowerMachNumber = 3.0   
UpperMachNumber = 3.0
EdgeDensity = 3e-2
InitialDensity = 0.03

EdgeElectronTemperature = 0.1
EdgeIonTemperature = 0.1
InitialElectronTemperature = 0.1
InitialIonTemperature = 0.1

#-------------------------------------------------------

IonSpecies = "Hydrogen"     # Options: "Hydrogen", "Deuterium", "DeuteriumTritium"

useNeutralsModel = false      # Compute CX using neutrals model
NeutralDensity = 0.0        # Background neutral density in m^-3

UniformHeatSource = 1000.0   # Add an initial uniform heat source for the electrons, decays exponentially at rate SourceRampup

#---------- Particle source settings ----------#
LowerPS = 500.0 # Base (uniform) particle source
UpperPS = 0.0 # Height of additional Gaussian
ParticleSourceCenter = 0.01 # R-location of UpperPS
ParticleSourceWidth = 0.01 # Width of UpperPS

#-----------------------------------------------

# Diffuse high gradient settings, threshold is the critical gradient to start adding diffusion, diffusivity is the coefficient
lowNDiffusivity = 0.01
lowNThreshold = 50.0
lowPDiffusivity = 0.01
lowPThreshold = 50.0
lowLDiffusivity = 0.01
lowLThreshold = 200.0

# Extra linear diffusion for electrons
TeDiffusivity = 0.1

transitionLength = 0.1