

[configuration]

TransportSystem = "LinearDiffusion"

PolynomialDegree = 3
GridSize = 30
LowerBoundary = -1.0
UpperBoundary =  1.0
t_final = 1.0
delta_t = 0.1

Relative_tolerance = 1.0e-3
Absolute_tolerance = 1.0e-3

[DiffusionProblem]

Kappa = 1.0
Centre = 0.0
SourceStrength = 3.5
InitialWidth = 0.1
UseMMS = false
growth = 0.0

