[configuration]
restart = false
TransportSystem = "MatrixDiffusion"

PolynomialDegree = 3
GridSize = 30
LowerBoundary = -1.0
UpperBoundary =  1.0

t_final = 0.025
delta_t = 0.001

Relative_tolerance = 1.0e-2
Absolute_tolerance = 1.0e-2

tau = 0.5

[DiffusionProblem]

nVars = 2
InitialHeights = [1.0,1.0]
Kappa = [1.0,0.0,
        0.0,1.0]