[configuration]

restart = false
RestartFile = "/home/eatocco/projects/MaNTA/runs/MirrorFusion.restart.nc"

MinStepSize = 1e-11
TransportSystem = "MirrorPlasma"

Polynomial_degree = 6
Grid_size = 30
High_Grid_Boundary = true
Lower_Boundary_Fraction = 0.2
Upper_Boundary_Fraction = 0.2

OutputPoints = 1000

Lower_boundary =  0.628318530717959
Upper_boundary =  15.5
tau = 100000.0
t_final = 1e-1
delta_t = 1e-4
Relative_tolerance = 1.0e-2
# Per-variable 
Absolute_tolerance = 1e-2

[MirrorPlasma]

lowerBoundaryConditions = [false,true,false,true]    # I found this combination to work the best, but results may vary 
upperBoundaryConditions = [false,false,false,true]

MinDensity = 0.0
MinTemp = 0.0
RelaxFactor = 0.0

SourceCap = 100000.0
SourceRampup =1e-4
useAmbipolarPhi = true
useConstantVoltage = true
PlasmaVoltage = 10e6
CurrentDecay = 1e-3

# gamma = 1.0
# gamma_d = 0.0
# gamma_h = 1e5

gamma = 10000.0
gamma_d = 100.0
gamma_h = 1e5

# ConstantProfiles = ["Density"]

Bz = 4.0
Rm = 6.0
Lz = 5.0
FieldSlope = 0.0

# IRadial = 10000.0
IRadial = 0.01
MachWidth = 0.1

EdgeDensity = 0.05
InitialDensity = 0.5

EdgeElectronTemperature = 0.5
EdgeIonTemperature = 0.5
InitialElectronTemperature = 1.0
InitialIonTemperature = 1.0

InitialMachNumber = 7.0
LowerMachNumber = 4.5
UpperMachNumber = 4.5

IonSpecies = "DeuteriumTritium"

UniformHeatSource = 100.0

useNeutralsModel = false
NeutralDensity = 0.0

# LowerPS = 2000.0
LowerPS = 10.0
# UpperPS = 500.0
# UpperPS = 30.0

# ParticleSourceWidth = 0.1
ParticleSourceCenter = 10.0
ParticleSourceWidth = 0.5

lowNDiffusivity = 0.01
lowNThreshold = 10.0
lowPDiffusivity = 0.01
lowPThreshold = 50.0
lowLDiffusivity = 0.01
lowLThreshold = 200.0

# Extra linear diffusion for electrons
TeDiffusivity = 0.1
transitionLength = 0.1
# transitionLength = 100000.0