[configuration]

restart = false
RestartFile = "/home/eatocco/projects/MaNTA/runs/MirrorFusion.restart.nc"

MinStepSize = 1e-11
TransportSystem = "MirrorPlasma"

Polynomial_degree = 5
Grid_size = 45
High_Grid_Boundary = true
Lower_Boundary_Fraction = 0.01
Upper_Boundary_Fraction = 0.01

OutputPoints = 1000

Lower_boundary =  0.628318530717959
Upper_boundary =  15.5
tau = 100000.0
t_final = 1e-1
delta_t = 1e-4
Relative_tolerance = 1.0e-2
# Per-variable 
Absolute_tolerance = 1e-2

[MirrorPlasma]

lowerBoundaryConditions = [false,false,false,true]    # I found this combination to work the best, but results may vary 
upperBoundaryConditions = [false,false,false,true]

MinDensity = 0.0
MinTemp = 0.0
RelaxFactor = 0.0

SourceCap = 100000.0
SourceRampup =5e-3
useAmbipolarPhi = true
useConstantVoltage = true
PlasmaVoltage = 5e6
CurrentDecay = 1e-2

# gamma = 1.0
# gamma_d = 0.0
# gamma_h = 1e5

gamma = 1000.0
gamma_d = 10.0
gamma_h = 1e2

# ConstantProfiles = ["Density"]

Bz = 4.0
Rm = 6.0
Lz = 5.0
FieldSlope = 0.05

# IRadial = 10000.0
IRadial = 0.05
MachWidth = 0.1

EdgeDensity = 0.1
InitialDensity = 0.1

EdgeElectronTemperature = 1.0
EdgeIonTemperature = 1.0
InitialElectronTemperature = 8.0
InitialIonTemperature = 8.0
InitialMachNumber = 7.0
LowerMachNumber = 3.5
UpperMachNumber = 3.5

IonSpecies = "DeuteriumTritium"

UniformHeatSource = 500.0

useNeutralsModel = false
NeutralDensity = 0.0

# LowerPS = 2000.0
LowerPS = 10.0
# UpperPS = 500.0
UpperPS = 15.0

# ParticleSourceWidth = 0.1
ParticleSourceCenter = 1.0
ParticleSourceWidth = 0.1

lowNDiffusivity = 1e-3
lowNThreshold = 0.01
lowPDiffusivity = 1e-3
lowPThreshold = 0.01
lowLDiffusivity = 0.01
lowLThreshold = 200.0

# Extra linear diffusion for electrons
TeDiffusivity = 0.001
transitionLength = 0.1
# transitionLength = 100000.0