
[configuration]
restart = false
RestartFile = "/home/eatocco/projects/MaNTA/runs/ScalarTestDot.restart.nc"

TransportSystem = "ScalarTestLD3"

PolynomialDegree = 3
GridSize = 5
LowerBoundary =  -1.0
UpperBoundary =   1.0

t_final = 1.0
delta_t = 0.1

Relative_tolerance = 1.0e-4
Absolute_tolerance = 1.0e-3

[DiffusionProblem]

gamma = 1.0
gamma_d = -0.1
gamma_I = -0.5
