from .config import MirrorPlasmaConfig
from .ion_species import DeuteriumTritium, Deuterium
import numpy as np

CMFX = MirrorPlasmaConfig(
    0.1,
    0.35,
    gamma=5e4,
    gamma_d=10.0,
    gamma_h=1e6,
    EdgeDensity=1e-2,
    InitialIonTemperatureHeight=0.2,
    InitialElectronTemperatureHeight=0.2,
    InitialMachNumber=8.0,
    EdgeMachNumber=4.0,
    Current=15.0,
    useConstantVoltage=True,
    useNeutralsModel=True,
    NeutralDensity=2e14,
    ParticleSourceHeight=10.0,
    ParticleSourceWidth=0.1,
    ParticleSourceCenter=0.2,
    MagneticFieldSlope=0.0,
    PlasmaVoltage=75e3,
    # IonSpecies=Deuterium(),
    ADCoefficient=0.1,
    ADDecayRates=0.5 * np.ones((4,)),
    ADFinalCoeffs=[0.2, 0.005, 0.01, 0.1],
)

CMFX1keV = MirrorPlasmaConfig(
    0.05,
    0.25,
    gamma=5e4,
    gamma_d=100.0,
    gamma_h=1e5,
    InitialIonTemperatureHeight=0.2,
    InitialElectronTemperatureHeight=0.2,
    InitialMachNumber=8.0,
    EdgeMachNumber=4.0,
    Current=15.0,
    useConstantVoltage=True,
    useNeutralsModel=True,
    NeutralDensity=1e14,
    ParticleSourceHeight=100.0,
    ParticleSourceWidth=0.1,
    ParticleSourceCenter=0.2,
    IonSpecies=Deuterium(),
    PlasmaVoltage=100e3,
    ADCoefficient=1.0,
)

Fusion = MirrorPlasmaConfig(
    0.1,
    0.5,
    gamma=0.5,
    gamma_d=1e-3,
    gamma_h=1.0,
    InitialMachNumber=8.0,
    EdgeMachNumber=5.0,
    EdgeDensity=0.1,
    EdgeElectronTemperature=0.4,
    InitialElectronTemperatureHeight=1.0,
    EdgeIonTemperature=0.4,
    InitialIonTemperatureHeight=1.0,
    InitialDensityHeight=0.2,
    NeutralDensity=1e13,
    PlasmaVoltage=8.0e6,
    MagneticFieldStrength=4.5,
    ParticleSourceHeight=10.0,
    ParticleSourceWidth=0.2,
    ParticleSourceCenter=0.3,
    Current=0.01,
    PlasmaLength=2.0,
    MirrorRatio=3.0,
    MagneticFieldSlope=0.2,
    useNeutralsModel=True,
    IonSpecies=DeuteriumTritium(),
    ADCoefficient=1.0,
    ADDecayRates=10.0 * np.ones((4,)),
    ADFinalCoeffs=[0.1, 0.01, 0.01, 5.0],
)
