from MirrorPlasma.Config import MirrorPlasmaConfig
from MirrorPlasma.IonSpecies import Hydrogen, DeuteriumTritium
from python.MirrorPlasma import IonSpecies
import numpy as np

CMFX = MirrorPlasmaConfig(
    0.1,
    0.35,
    gamma=5e4,
    gamma_d=10.0,
    gamma_h=1e6,
    EdgeDensity=1e-2,
    InitialIonTemperatureHeight=0.2,
    InitialElectronTemperatureHeight=0.2,
    InitialMachNumber=8.0,
    EdgeMachNumber=4.0,
    Current=15.0,
    useConstantVoltage=True,
    useNeutralsModel=True,
    NeutralDensity=2e14,
    ParticleSourceHeight=10.0,
    ParticleSourceWidth=0.1,
    ParticleSourceCenter=0.2,
    MagneticFieldSlope=0.0,
    PlasmaVoltage=80e3,
    ADCoefficient=0.2,
    ADFinalCoeffs=[0.1, 0.01, 0.05, 0.1],
)

CMFX1keV = MirrorPlasmaConfig(
    0.05,
    0.25,
    gamma=5e4,
    gamma_d=100.0,
    gamma_h=1e5,
    InitialIonTemperatureHeight=0.2,
    InitialElectronTemperatureHeight=0.2,
    InitialMachNumber=8.0,
    EdgeMachNumber=4.0,
    Current=15.0,
    useConstantVoltage=True,
    useNeutralsModel=True,
    NeutralDensity=1e14,
    ParticleSourceHeight=100.0,
    ParticleSourceWidth=0.1,
    ParticleSourceCenter=0.2,
    PlasmaVoltage=100e3,
    ADCoefficient=1.0,
)

Fusion = MirrorPlasmaConfig(
    0.1,
    0.5,
    gamma=0.1,
    gamma_d=1e-4,
    gamma_h=0.1,
    InitialMachNumber=8.0,
    EdgeMachNumber=5.0,
    EdgeDensity=0.02,
    InitialDensityHeight=0.2,
    NeutralDensity=5e12,
    PlasmaVoltage=5.0e6,
    MagneticFieldStrength=4.5,
    ParticleSourceHeight=20.0,
    ParticleSourceWidth=0.2,
    Current=0.1,
    PlasmaLength=4.0,
    ParticleSourceCenter=0.4,
    MirrorRatio=3.0,
    useNeutralsModel=True,
    IonSpecies=DeuteriumTritium(),
    ADCoefficient=5.0,
    ADDecayRates=0.5 * np.ones((4,)),
    ADFinalCoeffs=[0.1, 0.2, 0.2, 0.1],
)
